### ISSUE TITLE
Apple M1 linux/arm64 docker compose mount bind issue for bfren/apache-php:php5.6

### ISSUE THREAD

**Issue by splashmarkopolo** [bfren/docker-apache-php#36]
First of all, thanks for providing the Apple M1 support for apache and php 5.6. Working on setting it up via docker compose on the new M1 laptop. Came across the following issue. If I specify a bind mount on a single file, the container exits with the following:

- type: bind
        source: ./config/httpd.conf
        target: /etc/apache2/httpd.conf

docker-m1-webserver-1 exited with code 111

Folder based bind works though

- type: bind
        source: ./logs/apache
        target: /var/log/apache2

Issue seems to be with single file based bind mounts.

**Comment by splashmarkopolo** [comment]
some additional debug info

docker-m1-webserver-1  | [bf] 2022-04-06 22:31:26 | 11-config:  .. httpd.conf
docker-m1-webserver-1  | [bf] 2022-04-06 22:31:26 | 11-config: Error using template mv: can't rename '/tmp/tmp.jOlbBJ': Resource busy (bf-esh)
docker-m1-webserver-1  | [bf] 2022-04-06 22:31:26 | init: Unable to initialise container.
docker-m1-webserver-1  | [bf] 2022-04-06 22:31:26 | bf-env: BF_TERMINATING=1.
docker-m1-webserver-1  | [bf] 2022-04-06 22:31:26 | bf-cont-terminate: Terminating container, goodbye.
docker-m1-webserver-1  | s6-rc: info: service init successfully started

**Comment by bfren** [comment]
Ah ok, that looks like the template engine is trying to write the default httpd.conf - and Docker is refusing permission because it's a mount point.  I'll try to reproduce and then see how I can fix it.

**Comment by splashmarkopolo** [comment]
Great, thanks for the quick response. Much appreciated.

**Comment by bfren** [comment]
OK, if you try using the tag php5.6-dev and setting APACHE_USE_CUSTOM_CONF=1 in your run command / docker compose, you will be able to bind the httpd.conf file as you attempted.

**Comment by bfren** [comment]
(I don't have an M1 Mac so can't test, but I don't think the issue is related to that.)

**Comment by splashmarkopolo** [comment]
Thanks ... it now works for the httpd.conf file now but there is quite a few files I need to map for example php.ini and a few more.

docker-m1-webserver-1  | [bf] 2022-04-07 14:43:01 | 22-php-ini-config: session.gc_maxlifetime=86400. (replace-ini)
docker-m1-webserver-1  | sed: can't move '/etc/php5/php.inidAchCN' to '/etc/php5/php.ini': Resource busy
docker-m1-webserver-1  | [bf] 2022-04-07 14:43:01 | init: Unable to initialise container.
docker-m1-webserver-1  | [bf] 2022-04-07 14:43:01 | bf-env: BF_TERMINATING=1.
docker-m1-webserver-1  | [bf] 2022-04-07 14:43:01 | bf-cont-terminate: Terminating container, goodbye.

Would it be possible to extend this files other than httpd.conf? Really appreciate the quick turnaround. 

Thanks,
Mark

**Comment by bfren** [comment]
OK, I can extend it to php.ini - now if you set the PHP_INI environment variable to 'custom' the latest dev build won't try to download and modify the php.ini file.

See how you get on with that!  They are the only two generated files in the image I think, so you shouldn't see the same issue elsewhere.

**Comment by splashmarkopolo** [comment]
Excellent, that worked. Can't thank you enough.

**Comment by bfren** [comment]
Great, I'll merge the PR and release so you can switch off the dev tag.
